
development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: psyfog 
  password: icecast

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: psyfog  
  password: icecast